#============================================================================
# init.vim --- My SpaceVim config
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
#=============================================================================

# SpaceVim options {{{
[options]
    default_indent = 4
    enable_debug = 1
    enable_ale = 0
    filemanager = "defx"
    filetree_direction = "right"
    # enable_ycm = 1
    # snippet_engine = "ultisnips"
    line_on_the_fly = 0
    # default_custom_leader = "e"
    enable_statusline_mode = true
    # enable_ale = false
    # enable_neomake = false
    realtime_leader_guide = 1
    enable_tabline_filetype_icon = false
    enable_os_fileformat_icon = false
    statusline_unicode_symbols = false
    buffer_index_type = 4
    windows_index_type = 3
    statusline_separator = 'arrow'
    github_username = 'wsdjeg'
    auto_disable_touchpad = 0
    colorscheme = 'one'
    checkinstall = false
    guifont = 'SauceCodePro Nerd Font:h11:cANSI:qDRAFT'
    enable_tabline_filetype_icon = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    search_tools = ["rg", "pt", "ack", "grep", "findstr"]
    # autocomplete_method = "coc"
    commandline_prompt = '>'
    # vimcompatible = true
    # enable_language_specific_leader = false
    enable_statusline_tag = false
# }}}

# SpaceVim layer config {{{
[[layers]]
    name = 'denite'
[[layers]]
    name = 'format'
[[layers]]
    name = 'git'
[[layers]]
    name = 'tools'
[[layers]]
    name = 'tags'
[[layers]]
    name = 'VersionControl'
[[layers]]
    name = 'lang#vim'
[[layers]]
    name = 'lang#toml'
[[layers]]
    name = 'colorscheme'
[[layers]]
    name = 'core#statusline'
    enable = true
[[layers]]
    name = 'core#tabline'
    enable = true
[[layers]]
    name = 'autocomplete'
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"
[[layers]]
    name = 'lang#markdown'
    enableWcwidth = 1
    listItemIndent = 1
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30
